openapi: 3.0.3
info:
    title: Template Mobile App API
    description: This is a template API server using Go Gin framework
    version: "1.0"
    contact: {}
servers:
    - url: http://localhost:8080/api/v1
      description: Http server
paths:
    /health:
        get:
            tags:
                - health
            summary: Health check endpoint
            description: Returns the health status of the API
            responses:
                "200":
                    description: OK
    /posts:
        get:
            tags:
                - posts
            summary: Get all posts from JSONPlaceholder
            description: Fetch all posts from JSONPlaceholder API and return formatted response
            responses:
                "200":
                    description: OK
                "500":
                    description: Internal Server Error
    /posts/{id}:
        get:
            tags:
                - posts
            summary: Get a post by ID from JSONPlaceholder
            description: Fetch a specific post by ID from JSONPlaceholder API and return formatted response
            parameters:
                - name: id
                  in: path
                  description: Post ID
                  required: true
            responses:
                "200":
                    description: OK
                "400":
                    description: Bad Request
                "404":
                    description: Not Found
                "500":
                    description: Internal Server Error
components:
    schemas:
        main.ErrorResponse:
            type: object
            properties:
                error:
                    type: string
                    example: Internal server error
                message:
                    type: string
                    example: Failed to fetch data
        main.PostResponse:
            type: object
            properties:
                body:
                    type: string
                    example: Sample post body content
                formattedAt:
                    type: string
                    example: "2024-01-01T12:00:00Z"
                id:
                    type: integer
                    example: 1
                title:
                    type: string
                    example: Sample Post Title
                userId:
                    type: integer
                    example: 1
