openapi: 3.0.3
info:
  contact: {}
  description: This is a template API server using Go Gin framework
  title: Template Mobile App API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns the health status of the API
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
      summary: Health check endpoint
      tags:
        - health
  /posts:
    get:
      description: Fetch all posts from JSONPlaceholder API and return formatted response
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/main.PostResponse"
                type: array
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/main.ErrorResponse"
      summary: Get all posts from JSONPlaceholder
      tags:
        - posts
  "/posts/{id}":
    get:
      description: Fetch a specific post by ID from JSONPlaceholder API and return
        formatted response
      parameters:
        - description: Post ID
          in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/main.PostResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/main.ErrorResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/main.ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/main.ErrorResponse"
      summary: Get a post by ID from JSONPlaceholder
      tags:
        - posts
servers:
  - url: //localhost:8080/api/v1
components:
  schemas:
    main.ErrorResponse:
      properties:
        error:
          example: Internal server error
          type: string
        message:
          example: Failed to fetch data
          type: string
      type: object
    main.PostResponse:
      properties:
        body:
          example: Sample post body content
          type: string
        formattedAt:
          example: 2024-01-01T12:00:00Z
          type: string
        id:
          example: 1
          type: integer
        title:
          example: Sample Post Title
          type: string
        userId:
          example: 1
          type: integer
      type: object
